services:
  # Backend API service
  - type: web
    name: chat-app-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5002
    autoDeploy: true

  # Frontend service (only needed if you deploy separately, otherwise the backend serves the frontend)
  - type: web
    name: chat-app-frontend
    env: static
    region: ohio
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 